ALTER TABLE Todo_Contact DROP FOREIGN KEY FKTodo_Conta23185;
ALTER TABLE Todo_Contact DROP FOREIGN KEY FKTodo_Conta64317;
ALTER TABLE Todo DROP FOREIGN KEY FKTodo902816;
DROP TABLE IF EXISTS Todo_Contact;
DROP TABLE IF EXISTS Contact;
DROP TABLE IF EXISTS `User`;
DROP TABLE IF EXISTS Todo;